sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: S+wbV7M9dd8arz33vMVi6AN77PH8yTE5d0pMDr1yxnuSI9jOAHGRf4wSksjKKjMiKCLkCQprcfo8ZZBBTr1h4co4Y4oZjupOcq+dLAZ8jxPF+hR9K3v17y6ltmzCpXysxI6Q16Q0veM7isvcslvq/VZazM5TdDAnSSuLjuxIgp6zIbqzoYHm8sftT7zirM04QO2SSJ7QvD/RzilXqzi/FswM8hVt+qkGLOq2aWpRoDo6yF0wMjxq23lZdtDemJbKP/1YqFFb3a8LFebpvJyNzGo1zBjtzNhOYWHcYWwlHqiQHejK1dIiyUF2kogKwdc4nAMyowKNO02injIJLCUtPRuKZzEpe446xmwWnOVi4LKJ7zhfQcUSFDzVDdvG4ZGPaFNIHUwTAEXajjU1k0qDu/PlLoWjUFTk0V9T0Ui1nLhqwdUth/ueGVEek7FNDyB6Wy5HY3ZGExi4PFkHEqtkXVj1zppL/fG90zLT5mgQ8BYCPEugYnMQ8NtTnGp31QsDHJZLzoWb5PJDIaxqJcqOxym1p69tFlhszXkkpWf7xAOd0vUWSACZQPQ1CYCiX7G4fQQYXYIXbFm22WBXkQMY7LuwfwCYNc8iJDSNVVBDt8XRCQxsVwc0DvakzdUauGSoCjHuZpqOlTJ/CMQ4x3aMWCbgCW0epcInEtty6aP8PSw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Through-the-Magic-Door_5317
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy